name: Deploy

on:
  workflow_dispatch: # Trigger deployment manually

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: List workspace contents for debugging
      run: ls -R ${{ github.workspace }}

    - name: Print environment variables
      run: env
    
    - name: Print GITHUB_WORKSPACE
      run: |
        echo ${{ github.workspace }}
        ls -R ${{ github.workspace }}

    - name: Verify Frontend directory
      run: |
        if [ -d "${{ github.workspace }}/Frontend" ]; then
          echo "Frontend directory exists."
        else
          echo "Frontend directory does not exist."
          exit 1
        fi

    - name: Remove existing files on remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo rm -rf $BITNAMI_HT_DOCS_DIRECTORY/*

    - name: Transfer files using scp
      run: |
        scp -r -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ github.workspace }}/Frontend/* ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:$BITNAMI_HT_DOCS_DIRECTORY

    - name: Restart Apache on remote server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo /opt/bitnami/ctlscript.sh restart apache